apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: supermock
spec:
  replicas: 2 # Меньше реплик для dev-окружения
  template:
    spec:
      containers:
        - name: backend
          image: ${DOCKER_USERNAME}/supermock-backend:develop # Используем тег develop для dev-окружения
          resources:
            requests:
              memory: '128Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
              cpu: '150m'
