FROM nginx:alpine

# Копируем нашу конфигурацию в контейнер
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Создаем директории для логов
RUN mkdir -p /var/log/nginx

# Экспонируем порты 8080 и 8443
EXPOSE 8080 8443

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]