version: '3.8'
services:
  mongo:
    image: mongo:5
    ports:
      - '0.0.0.0:27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - '0.0.0.0:6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: always
    command: redis-server --appendonly yes

volumes:
  mongo-data:
  redis-data:

networks:
  app-network:
    driver: bridge
