version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: supermock-postgres-dev
    environment:
      POSTGRES_DB: supermock_dev
      POSTGRES_USER: supermock
      POSTGRES_PASSWORD: supermock123
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supermock -d supermock_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: supermock-redis-dev
    ports:
      - '0.0.0.0:6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: always
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: bridge
