apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: supermock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: supermock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
