apiVersion: v1
kind: Secret
metadata:
  name: supermock-secrets
  namespace: supermock
type: Opaque
data:
  # Эти значения должны быть заменены на реальные закодированные в base64
  # Пример: echo -n "your-secret" | base64
  JWT_SECRET: ${JWT_SECRET_BASE64}
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME_BASE64}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD_BASE64}
  REDIS_PASSWORD: ${REDIS_PASSWORD_BASE64}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID_BASE64}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET_BASE64}
  GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL_BASE64}
  FRONTEND_URL: ${FRONTEND_URL_BASE64}
