version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - '8200:8200'
    restart: always
    volumes:
      - ./config:/vault/config
      - vault-data:/vault/data
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID:-supermock-root-token}
    command: server -config=/vault/config/vault.hcl
    networks:
      - vault-network
      - app-network

volumes:
  vault-data:

networks:
  vault-network:
    driver: bridge
  app-network:
    external: true
