#!/bin/bash

# Script to enable development test accounts
# This script creates or updates the .env.development file to enable test accounts

FRONTEND_DIR="frontend"
ENV_FILE="$FRONTEND_DIR/.env.development"

echo "🔧 Enabling development test accounts..."

# Check if frontend directory exists
if [ ! -d "$FRONTEND_DIR" ]; then
    echo "❌ Frontend directory not found: $FRONTEND_DIR"
    exit 1
fi

# Create .env.development file if it doesn't exist
if [ ! -f "$ENV_FILE" ]; then
    echo "📝 Creating new .env.development file..."
    cat > "$ENV_FILE" << EOF
# Development Environment Variables
# Generated by enable-dev-test-accounts.sh

# Telegram Bot Configuration
VITE_TELEGRAM_BOT_NAME=your_bot_name
VITE_TELEGRAM_BOT_ID=your_bot_id

# API Configuration
VITE_API_URL=http://localhost:3000

# Development Features
VITE_ENABLE_DEMO_MODE=false
VITE_ENABLE_DEV_TEST_ACCOUNTS=true

# WebRTC Configuration
VITE_JITSI_URL=https://meet.jit.si
VITE_STUN_URLS=stun:stun.l.google.com:19302,stun:global.stun.twilio.com:3478
VITE_TURN_URL=
VITE_TURN_USERNAME=
VITE_TURN_PASSWORD=
EOF
    echo "✅ Created new .env.development file with test accounts enabled"
else
    echo "📝 Updating existing .env.development file..."
    
    # Check if VITE_ENABLE_DEV_TEST_ACCOUNTS already exists
    if grep -q "VITE_ENABLE_DEV_TEST_ACCOUNTS" "$ENV_FILE"; then
        # Update existing line
        sed -i 's/VITE_ENABLE_DEV_TEST_ACCOUNTS=.*/VITE_ENABLE_DEV_TEST_ACCOUNTS=true/' "$ENV_FILE"
        echo "✅ Updated VITE_ENABLE_DEV_TEST_ACCOUNTS=true"
    else
        # Add new line
        echo "VITE_ENABLE_DEV_TEST_ACCOUNTS=true" >> "$ENV_FILE"
        echo "✅ Added VITE_ENABLE_DEV_TEST_ACCOUNTS=true"
    fi
fi

echo ""
echo "🎉 Development test accounts are now enabled!"
echo ""
echo "To use test accounts:"
echo "1. Restart your development server"
echo "2. Go to the debug page (/dev-test)"
echo "3. Use the 'Test Accounts' section to switch between accounts"
echo ""
echo "Available test accounts:"
echo "- Test Candidate (Frontend Developer)"
echo "- Test Interviewer (Senior Developer)"
echo "- Demo User (Full Stack Developer)"
echo "- Random account generator"
echo ""
echo "Note: Test accounts are only available in development mode and will be completely disabled in production."
