apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: supermock
  labels:
    app: backend
  annotations:
    service.kubernetes.io/description: 'Blue-Green deployment service for backend'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  # По умолчанию направляем трафик на blue версию
  # Для переключения на green версию нужно изменить селектор
  selector:
    app: backend
    version: blue
---
# Сервис для тестирования green версии перед переключением
apiVersion: v1
kind: Service
metadata:
  name: backend-preview
  namespace: supermock
  labels:
    app: backend
    role: preview
  annotations:
    service.kubernetes.io/description: 'Preview service for testing the inactive deployment'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  # Всегда направляет трафик на green версию для тестирования
  selector:
    app: backend
    version: green
