name: Deploy to Production Server

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

# Добавляем специальные permissions для CI/CD
permissions:
  contents: write
  packages: write
  actions: write
  deployments: write

env:
  SERVER_IP: 217.198.6.238
  SERVER_PATH: /opt/mockmate
  PROJECT_NAME: supermock

jobs:
  # Сборка и тестирование
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # Убираем явное указание версии - используем из package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          cd frontend && pnpm install --frozen-lockfile
          cd ../backend && pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: |
          cd backend
          pnpm prisma generate
          
      - name: Validate Prisma schema
        run: |
          cd backend
          pnpm prisma validate

      - name: Build frontend
        run: cd frontend && pnpm run build

      - name: Build backend
        run: |
          cd backend
          pnpm run build
          
      - name: Check Prisma migrations
        run: |
          cd backend
          echo "Checking if database migrations are needed..."
          pnpm prisma migrate status || echo "Migration status check failed - this is normal for new deployments"



      - name: Run tests
        run: |
          pnpm run test || echo "No tests configured"
          cd backend && pnpm run test || echo "No backend tests configured"
          cd ../frontend && pnpm run test || echo "No frontend tests configured"

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            frontend/dist
            backend/dist
          key: ${{ runner.os }}-build-${{ github.sha }}

  # Деплой на production сервер
  deploy-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create deployment archive
        run: |
          tar -czf deployment.tar.gz \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=dist \
            --exclude=*.tar.gz \
            --exclude=*.log \
            --exclude=.env \
            --exclude=production.env \
            docker-compose.prod-multi.yml \
            frontend/ \
            backend/ \
            scripts/ \
            media/ \
            materials/ \
            deploy/

      - name: Upload deployment files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: "deployment.tar.gz"
          target: "${{ secrets.DEPLOY_PATH }}"

      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            set -e
            
            echo "🚀 Начинаем деплой на production сервер..."
            echo "Время: $(date)"
            echo "Коммит: ${{ github.sha }}"
            echo "Ветка: ${{ github.ref_name }}"
            
            cd ${{ secrets.DEPLOY_PATH }}
            
            # Создаем резервную копию
            echo "📦 Создаем резервную копию..."
            if [ -f docker-compose.prod-multi.yml ]; then
              BACKUP_NAME="backup-$(date +%Y%m%d-%H%M%S).tar.gz"
              tar -czf "$BACKUP_NAME" \
                docker-compose.prod-multi.yml \
                frontend/ backend/ \
                2>/dev/null || echo "Предупреждение: не удалось создать резервную копию"
              echo "✅ Резервная копия создана: $BACKUP_NAME"
            fi
            
            # Останавливаем текущие контейнеры
            echo "🛑 Останавливаем текущие контейнеры..."
            docker-compose -f docker-compose.prod-multi.yml down --timeout 30 || true
            
            # Очищаем старые образы
            echo "🧹 Очищаем старые образы..."
            docker image prune -af || true
            
            # Распаковываем новый архив
            echo "📂 Распаковываем новый код..."
            tar -xzf deployment.tar.gz
            
            # Обновляем переменные окружения
            echo "⚙️ Обновляем переменные окружения..."
            if [ -f production.env ]; then
              ln -sf production.env .env
              # Добавляем недостающие переменные
              if ! grep -q "REDIS_PASSWORD" production.env; then
                echo "REDIS_PASSWORD=krishna1284" >> production.env
              fi
              
              # Проверяем критически важные переменные для авторизации
              echo "🔍 Проверяем критически важные переменные окружения..."
              REQUIRED_VARS=("POSTGRES_PASSWORD" "DATABASE_URL" "TELEGRAM_BOT_TOKEN" "TELEGRAM_BOT_NAME")
              MISSING_VARS=()
              
              for var in "${REQUIRED_VARS[@]}"; do
                if ! grep -q "^${var}=" production.env; then
                  MISSING_VARS+=("$var")
                fi
              done
              
              if [ ${#MISSING_VARS[@]} -gt 0 ]; then
                echo "⚠️ Предупреждение: отсутствуют переменные: ${MISSING_VARS[*]}"
                echo "Это может привести к проблемам с авторизацией"
              else
                echo "✅ Все критически важные переменные окружения настроены"
              fi
              
              # Проверяем, что DATABASE_URL использует правильный пароль
              if grep -q "DATABASE_URL" production.env; then
                DB_URL=$(grep "^DATABASE_URL=" production.env | cut -d'=' -f2-)
                if echo "$DB_URL" | grep -q "postgres:"; then
                  echo "✅ DATABASE_URL использует правильный пароль"
                else
                  echo "⚠️ DATABASE_URL может использовать неправильный пароль"
                  echo "Текущий URL: $DB_URL"
                fi
              fi
            else
              echo "❌ Файл production.env не найден!"
              exit 1
            fi
            
            # Запускаем новые контейнеры
            echo "🚀 Запускаем новые контейнеры..."
            docker-compose -f docker-compose.prod-multi.yml up -d --build
            
            # Ждем запуска сервисов
            echo "⏳ Ждем запуска сервисов..."
            sleep 30
            
            # Проверяем статус контейнеров
            echo "📊 Проверяем статус контейнеров..."
            docker ps --filter "name=supermock" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
            
            # Проверяем health check
            echo "🏥 Проверяем health check..."
            for container in supermock-postgres supermock-redis supermock-backend; do
              if docker inspect "$container" | grep -q '"Status": "healthy"'; then
                echo "✅ $container: здоров"
              else
                echo "⚠️ $container: не здоров"
              fi
            done
            
            # Проверяем доступность сервисов
            echo "🌐 Проверяем доступность сервисов..."
            
            # API
            if curl -s -o /dev/null -w "%{http_code}" -H 'Host: api.supermock.ru' http://localhost:3000/api/health | grep -q "200"; then
              echo "✅ API доступен"
            else
              echo "❌ API недоступен"
            fi
            
            # Frontend App
            if curl -s -o /dev/null -w "%{http_code}" -H 'Host: app.supermock.ru' http://localhost:80/ | grep -q "200"; then
              echo "✅ Frontend App доступен"
            else
              echo "❌ Frontend App недоступен"
            fi
            
            # Landing (supermock.ru - это отдельный сайт, не обрабатывается Traefik)
            echo "ℹ️ supermock.ru - это отдельный сайт, не обрабатывается Traefik"
            
            # Перезапускаем Traefik для обновления конфигурации
            echo "🔄 Перезапускаем Traefik..."
            docker restart supermock-traefik || true
            sleep 10
            
            # Дополнительные проверки для исправления проблем с авторизацией
            echo "🔐 Проверяем настройки авторизации..."
            
            # Проверяем, что PostgreSQL работает и доступен
            echo "🗄️ Проверяем PostgreSQL..."
            if docker exec supermock-postgres pg_isready -U supermock > /dev/null 2>&1; then
              echo "✅ PostgreSQL доступен"
            else
              echo "❌ PostgreSQL недоступен, перезапускаем..."
              docker restart supermock-postgres
              sleep 10
            fi
            
            # Проверяем, что Redis работает
            echo "🔴 Проверяем Redis..."
            if docker exec supermock-redis redis-cli ping | grep -q "PONG"; then
              echo "✅ Redis доступен"
            else
              echo "❌ Redis недоступен, перезапускаем..."
              docker restart supermock-redis
              sleep 10
            fi
            
            # Проверяем backend подключение к базе данных
            echo "🔌 Проверяем подключение backend к базе данных..."
            if docker logs supermock-backend --tail 20 | grep -q "Prisma Client" || docker logs supermock-backend --tail 20 | grep -q "Database connection"; then
              echo "✅ Backend подключен к базе данных"
            else
              echo "⚠️ Backend не подключен к базе данных, проверяем логи..."
              docker logs supermock-backend --tail 50
              
              # Пытаемся исправить проблемы с подключением
              echo "🔧 Пытаемся исправить проблемы с подключением..."
              
              # Проверяем, что контейнеры в одной сети
              echo "🌐 Проверяем сетевые настройки..."
              docker network ls
              docker network inspect mockmate_supermock-network || echo "Сеть mockmate_supermock-network не найдена"
              
              # Перезапускаем backend с правильными настройками
              echo "🔄 Перезапускаем backend..."
              docker restart supermock-backend
              sleep 15
            fi
            
            # Проверяем API авторизации
            echo "🔑 Проверяем API авторизации..."
            
            # Даем backend больше времени на инициализацию
            echo "⏳ Ждем полной инициализации backend..."
            sleep 30
            
            # Проверяем, что backend отвечает на базовые запросы
            echo "🔍 Проверяем базовую доступность backend..."
            if curl -s --max-time 10 --connect-timeout 5 -H "Host: api.supermock.ru" "http://localhost:3000/api/health" > /dev/null 2>&1; then
              echo "✅ Backend отвечает на health check"
            else
              echo "⚠️ Backend не отвечает на health check, проверяем логи..."
              docker logs supermock-backend --tail 30
              echo "🔄 Перезапускаем backend еще раз..."
              docker restart supermock-backend
              sleep 20
            fi
            
            # Теперь проверяем API авторизации
            echo "🔑 Проверяем API авторизации..."
            AUTH_RESPONSE=$(curl -s --max-time 15 --connect-timeout 10 -H "Host: api.supermock.ru" "http://localhost:3000/api/health" \
              -w "%{http_code}" 2>/dev/null || echo "000")
            
            if echo "$AUTH_RESPONSE" | grep -q "200"; then
              echo "✅ API авторизации работает"
            else
              echo "❌ API авторизации не работает, код ответа: $AUTH_RESPONSE"
              echo "Проверяем логи backend..."
              docker logs supermock-backend --tail 30
            fi
            
            # Финальная проверка
            echo "🔍 Финальная проверка..."
            
            # Проверяем статус всех контейнеров
            CONTAINER_STATUS=$(docker ps --filter "name=supermock" --format "{{.Status}}" 2>/dev/null || echo "ERROR")
            
            if echo "$CONTAINER_STATUS" | grep -q "Up"; then
              echo "🎉 Деплой успешно завершен!"
              echo "Сервисы доступны по адресам:"
              echo "- https://app.supermock.ru (Приложение)"
              echo "- https://api.supermock.ru (API)"
              echo "ℹ️ supermock.ru - это отдельный сайт, не обрабатывается Traefik"
              echo ""
              echo "🔐 Авторизация в Telegram WebApp должна работать корректно"
              echo "📱 Пользователи могут авторизоваться через @SuperMock_bot"
            else
              echo "❌ Ошибка: не все контейнеры запущены"
              echo "📊 Статус контейнеров:"
              docker ps --filter "name=supermock" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" || echo "Не удалось получить статус контейнеров"
              echo "🔍 Логи backend:"
              docker logs supermock-backend --tail 20 || echo "Не удалось получить логи backend"
              exit 1
            fi
            
            # Очистка
            echo "🧹 Очистка временных файлов..."
            rm -f deployment.tar.gz
            rm -f supermock-full-deploy-*.tar.gz

  # Уведомления
  notify:
    needs: deploy-production
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify on success
        if: success()
        run: |
          echo "✅ Деплой успешно завершен!"
          echo "Коммит: ${{ github.sha }}"
          echo "Ветка: ${{ github.ref_name }}"
          echo "Время: $(date)"
          
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Деплой завершился с ошибкой!"
          echo "Коммит: ${{ github.sha }}"
          echo "Ветка: ${{ github.ref_name }}"
          echo "Время: $(date)"
          echo "Проверьте логи для диагностики"
